version: '3'
services:
  db:
    image: postgres
    volumes:
      - pgsql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=pwd
  web:
    build: .
    command: /bin/sh -c "rm -f /home/app/tmp/pids/server.pid && bundle exec rails s -p 9000 -b '0.0.0.0'"
    volumes:
      - .:/home/app
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
volumes:
  pgsql: